import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerSubnetTools } from "./tools/subnet.js";
import { registerMetagraphTools } from "./tools/metagraph.js";
import { registerValidatorTools } from "./tools/validator.js";
import { registerPriceTools } from "./tools/price.js";
import { registerNetworkTools } from "./tools/network.js";
import { registerIdentityTools } from "./tools/identity.js";
import { registerEventTools } from "./tools/events.js";
import { registerSearchTools } from "./tools/search-chain.js";
import { registerPortfolioTools } from "./tools/portfolio.js";
import { registerLearnTools } from "./tools/learn.js";
import { registerBalanceTools } from "./tools/balance.js";
import { registerWalletTools } from "./tools/wallet.js";
import { registerStakeTools } from "./tools/stake.js";
import { registerTransferTools } from "./tools/transfer.js";
import { registerConfirmTools } from "./tools/confirm.js";
import { registerSwapTools } from "./tools/swap.js";
import { registerExplainTools } from "./tools/explain.js";
import { registerConfigTools } from "./tools/config.js";
import { registerWebSearchTools } from "./tools/search-web.js";

export function registerTools(server: McpServer): void {
  registerSubnetTools(server);
  registerMetagraphTools(server);
  registerValidatorTools(server);
  registerPriceTools(server);
  registerNetworkTools(server);
  registerIdentityTools(server);
  registerEventTools(server);
  registerSearchTools(server);
  registerPortfolioTools(server);
  registerLearnTools(server);
  registerBalanceTools(server);
  registerWalletTools(server);
  registerStakeTools(server);
  registerTransferTools(server);
  registerConfirmTools(server);
  registerSwapTools(server);
  registerExplainTools(server);
  registerConfigTools(server);
  registerWebSearchTools(server);
}
